// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// add_two_cpp
double add_two_cpp(double x, double y);
RcppExport SEXP _EpiFusion_add_two_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(add_two_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// epifusion_compute_rt_cpp
Rcpp::NumericVector epifusion_compute_rt_cpp(Rcpp::IntegerVector infections, Rcpp::NumericVector gen_time);
RcppExport SEXP _EpiFusion_epifusion_compute_rt_cpp(SEXP infectionsSEXP, SEXP gen_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type infections(infectionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gen_time(gen_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(epifusion_compute_rt_cpp(infections, gen_time));
    return rcpp_result_gen;
END_RCPP
}
// epi_loglik_poisson_tp_cpp
Rcpp::NumericVector epi_loglik_poisson_tp_cpp(Rcpp::NumericMatrix positive_tests_tp, Rcpp::IntegerVector incidence);
RcppExport SEXP _EpiFusion_epi_loglik_poisson_tp_cpp(SEXP positive_tests_tpSEXP, SEXP incidenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type positive_tests_tp(positive_tests_tpSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type incidence(incidenceSEXP);
    rcpp_result_gen = Rcpp::wrap(epi_loglik_poisson_tp_cpp(positive_tests_tp, incidence));
    return rcpp_result_gen;
END_RCPP
}
// epi_loglik_poisson_pt_cpp
Rcpp::NumericVector epi_loglik_poisson_pt_cpp(Rcpp::NumericMatrix positive_tests_pt, Rcpp::IntegerVector incidence);
RcppExport SEXP _EpiFusion_epi_loglik_poisson_pt_cpp(SEXP positive_tests_ptSEXP, SEXP incidenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type positive_tests_pt(positive_tests_ptSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type incidence(incidenceSEXP);
    rcpp_result_gen = Rcpp::wrap(epi_loglik_poisson_pt_cpp(positive_tests_pt, incidence));
    return rcpp_result_gen;
END_RCPP
}
// epi_only_poisson_pf_cpp
Rcpp::List epi_only_poisson_pf_cpp(Rcpp::IntegerVector incidence, double beta, double gamma, double phi, int initial_state, int num_particles, int seed);
RcppExport SEXP _EpiFusion_epi_only_poisson_pf_cpp(SEXP incidenceSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP phiSEXP, SEXP initial_stateSEXP, SEXP num_particlesSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type incidence(incidenceSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< int >::type num_particles(num_particlesSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(epi_only_poisson_pf_cpp(incidence, beta, gamma, phi, initial_state, num_particles, seed));
    return rcpp_result_gen;
END_RCPP
}
// epi_only_poisson_pf_window_cpp
Rcpp::List epi_only_poisson_pf_window_cpp(Rcpp::IntegerVector observation_counts, Rcpp::IntegerVector observation_times, double initial_beta, double beta_jitter, double beta_refactor, double gamma, double phi, int initial_state, int num_particles, int seed);
RcppExport SEXP _EpiFusion_epi_only_poisson_pf_window_cpp(SEXP observation_countsSEXP, SEXP observation_timesSEXP, SEXP initial_betaSEXP, SEXP beta_jitterSEXP, SEXP beta_refactorSEXP, SEXP gammaSEXP, SEXP phiSEXP, SEXP initial_stateSEXP, SEXP num_particlesSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type observation_counts(observation_countsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type observation_times(observation_timesSEXP);
    Rcpp::traits::input_parameter< double >::type initial_beta(initial_betaSEXP);
    Rcpp::traits::input_parameter< double >::type beta_jitter(beta_jitterSEXP);
    Rcpp::traits::input_parameter< double >::type beta_refactor(beta_refactorSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< int >::type num_particles(num_particlesSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(epi_only_poisson_pf_window_cpp(observation_counts, observation_times, initial_beta, beta_jitter, beta_refactor, gamma, phi, initial_state, num_particles, seed));
    return rcpp_result_gen;
END_RCPP
}
// run_mh_chain_looseformbeta_cpp
Rcpp::List run_mh_chain_looseformbeta_cpp(Rcpp::IntegerVector observation_counts, Rcpp::IntegerVector observation_times, int n_steps, int num_particles, int initial_state, double beta_refactor, Rcpp::NumericVector init_params, Rcpp::NumericVector proposal_sds, Rcpp::NumericVector lower_bounds, Rcpp::NumericVector upper_bounds, int seed);
RcppExport SEXP _EpiFusion_run_mh_chain_looseformbeta_cpp(SEXP observation_countsSEXP, SEXP observation_timesSEXP, SEXP n_stepsSEXP, SEXP num_particlesSEXP, SEXP initial_stateSEXP, SEXP beta_refactorSEXP, SEXP init_paramsSEXP, SEXP proposal_sdsSEXP, SEXP lower_boundsSEXP, SEXP upper_boundsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type observation_counts(observation_countsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type observation_times(observation_timesSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type num_particles(num_particlesSEXP);
    Rcpp::traits::input_parameter< int >::type initial_state(initial_stateSEXP);
    Rcpp::traits::input_parameter< double >::type beta_refactor(beta_refactorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type init_params(init_paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type proposal_sds(proposal_sdsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower_bounds(lower_boundsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_bounds(upper_boundsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mh_chain_looseformbeta_cpp(observation_counts, observation_times, n_steps, num_particles, initial_state, beta_refactor, init_params, proposal_sds, lower_bounds, upper_bounds, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EpiFusion_add_two_cpp", (DL_FUNC) &_EpiFusion_add_two_cpp, 2},
    {"_EpiFusion_epifusion_compute_rt_cpp", (DL_FUNC) &_EpiFusion_epifusion_compute_rt_cpp, 2},
    {"_EpiFusion_epi_loglik_poisson_tp_cpp", (DL_FUNC) &_EpiFusion_epi_loglik_poisson_tp_cpp, 2},
    {"_EpiFusion_epi_loglik_poisson_pt_cpp", (DL_FUNC) &_EpiFusion_epi_loglik_poisson_pt_cpp, 2},
    {"_EpiFusion_epi_only_poisson_pf_cpp", (DL_FUNC) &_EpiFusion_epi_only_poisson_pf_cpp, 7},
    {"_EpiFusion_epi_only_poisson_pf_window_cpp", (DL_FUNC) &_EpiFusion_epi_only_poisson_pf_window_cpp, 10},
    {"_EpiFusion_run_mh_chain_looseformbeta_cpp", (DL_FUNC) &_EpiFusion_run_mh_chain_looseformbeta_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_EpiFusion(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
