# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_two_cpp <- function(x, y) {
    .Call(`_EpiFusion_add_two_cpp`, x, y)
}

epifusion_compute_rt_cpp <- function(infections, gen_time) {
    .Call(`_EpiFusion_epifusion_compute_rt_cpp`, infections, gen_time)
}

epi_loglik_poisson_tp_cpp <- function(positive_tests_tp, incidence) {
    .Call(`_EpiFusion_epi_loglik_poisson_tp_cpp`, positive_tests_tp, incidence)
}

epi_loglik_poisson_pt_cpp <- function(positive_tests_pt, incidence) {
    .Call(`_EpiFusion_epi_loglik_poisson_pt_cpp`, positive_tests_pt, incidence)
}

epi_only_poisson_pf_cpp <- function(incidence, beta, gamma, phi, initial_state, num_particles, seed) {
    .Call(`_EpiFusion_epi_only_poisson_pf_cpp`, incidence, beta, gamma, phi, initial_state, num_particles, seed)
}

epi_only_poisson_pf_window_cpp <- function(observation_counts, observation_times, initial_beta, beta_jitter, beta_refactor, gamma, phi, initial_state, num_particles, seed) {
    .Call(`_EpiFusion_epi_only_poisson_pf_window_cpp`, observation_counts, observation_times, initial_beta, beta_jitter, beta_refactor, gamma, phi, initial_state, num_particles, seed)
}

run_mh_chain_looseformbeta_cpp <- function(observation_counts, observation_times, n_steps, num_particles, initial_state, beta_refactor, init_params, proposal_sds, prior_means, prior_sds, lower_bounds, upper_bounds, seed) {
    .Call(`_EpiFusion_run_mh_chain_looseformbeta_cpp`, observation_counts, observation_times, n_steps, num_particles, initial_state, beta_refactor, init_params, proposal_sds, prior_means, prior_sds, lower_bounds, upper_bounds, seed)
}

